version: '3'
services:
  webapp_woncept:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - serverside_session
    ports:
      - "5000:5000"
    container_name: WebApp_Concept
    
  serverside_session:
    image: redis
    ports:
      - "6379:6379"
    container_name: ServerSide_Session
