openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /auth/login:
    post:
      summary: User login
      description: Endpoint to authenticate users and retrieve a token.
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /auth/signup:
    post:
      summary: User registration
      description: Endpoint to register a new user.
      requestBody:
        description: User to register
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '201':
          description: Registration successful
        '400':
          description: Invalid input